version: '3.9'
services:
  fe-service:
    container_name: fe_container
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:80
    env_file: ./client/.env
    environment:
      - NODE_ENV=development
  be-service:
    container_name: be_container
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
