version: '3.9'
services:
  fe-service:
    container_name: fe_container
    image: 976002590783.dkr.ecr.us-east-1.amazonaws.com/final-app:fe-social
    restart: always
    ports:
      - 3000:80

    environment:
      - NODE_ENV=production
  be-service:
    container_name: be_container
    image: 976002590783.dkr.ecr.us-east-1.amazonaws.com/final-app:backend
    restart: always
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
