version: '3.9'
services:
  fe-service:
    container_name: fe_container
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:80
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4000
  be-service:
    container_name: be_container
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
